apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
    ports:
     - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"  
