apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: voting-app
    name: result-app-pod