apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-pod
      app: voting-app
  template:
    metadata:
      labels:
        name: voting-app-pod
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
