apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-deploy
      app: voting-app
  template:
    metadata:
      labels:
        name: worker-deploy
        app: voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
        ports:
         - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"  